### ISSUE TITLE
not working with wkhtmltopdf

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [emran-alhaddad/Saudi-Riyal-Font#12]
wkhtmltopdf 0.12.5 (with patched qt)

<img width="263" alt="Image" src="https://github.com/user-attachments/assets/6759c329-9fc7-45fa-9357-90d7bac03f87" />

**Comment by emran-alhaddad** [comment]
@ahmedsayedabdelsalam can you provide more details, framework and its version, sample code of configuration the library?

**Comment by ahmedsayedabdelsalam** [comment]
"php": "^8.2"
"laravel/framework": "^11.0"
"barryvdh/laravel-snappy": "^1.0"


```
<!doctype html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body {
            margin: 0px;
            width: 100%;
            padding: 0px;
            word-break: break-word;
            -webkit-font-smoothing: antialiased
        }

        .font-sans {
            font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important
        }

        @font-face{
            font-family:'saudi_riyal';
            src: url(data:font/truetype;charset=utf-8;base64,AAEAAAANAIAAAwBQRkZUTaImEXUAAAc0AAAAHEdERUYAOwANAAAHEAAAACRPUy8yVkJa4AAAAVgAAABWY21hcAA179MAAAHIAAABUmdhc3D//wADAAAHCAAAAAhnbHlmXC2lxAAAAywAAAHUaGVhZCt9vCAAAADcAAAANmhoZWEHtwSTAAABFAAAACRobXR4DJ4BeAAAAbAAAAAYbG9jYQCcATgAAAMcAAAAEG1heHAASwA1AAABOAAAACBuYW1l7GTerwAABQAAAAGzcG9zdI0SaQEAAAa0AAAAVAABAAAAAQAAkjtPw18PPPUACwQAAAAAAOPpO8IAAAAA4+k7wgC8ABYD0QOJAAAACAACAAAAAAAAAAEAAAOJAAAAXASNAAAAAAPRAAEAAAAAAAAAAAAAAAAAAAAFAAEAAAAHADIAAgAAAAAAAgAAAAEAAQAAAEAAAAAAAAAAAQOEAZAABQAIApkCzAAAAI8CmQLMAAAB6wAzAQkAAAIABQMAAAAAAAAAAAABEAAAAAAAAAAAAAAAUGZFZABAACDpAAPA/8AAXAOJ/+oAAAABAAAAAAAABAAAAAAAAAABVQAAAgAAAASNALwAvAC8AAAAAwAAAAMAAAAcAAEAAAAAAEwAAwABAAAAHAAEADAAAAAIAAgAAgAAAAAAIOkA//8AAAAAACDpAP//AAD/4xcEAAEAAAAAAAAAAAAAAQYAAAEAAAAAAAAAAQIAAAACAAAAAAAAAAAAAAAAAAAAAQAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATgCcAOoAAgC8ABYD0QOJAAcAMQAAJQYHFSU2NzUnNjc1BzU3Njc1BxEGByMRBxEGDwERBwYHFTcVBwYHFSU2PwE2NTE1NxUCpxUGASoVBhsVBujNFQboNiYBXTYmAc8WBer7FQYBByETMAhdey41AkAuNQFaLjUBMV8rLjUCMQFVHy/+5RQBqx4vAf6PLC41ATF3NS81ATgHG0gMDmkUvgAAAgC8ABYD0QOJAAcAMQAAJQYHFSU2NzUnNjc1BzU3Njc1BxEGByMRBxEGDwERBwYHFTcVBwYHFSU2PwE2NTE1NxUCpxUGASoVBhsVBujNFQboNiYBXTYmAc8WBer7FQYBByETMAhdey41AkAuNQFaLjUBMV8rLjUCMQFVHy/+5RQBqx4vAf6PLC41ATF3NS81ATgHG0gMDmkUvgAAAgC8ABYD0QOJAAcAMQAAJQYHFSU2NzUnNjc1BzU3Njc1BxEGByMRBxEGDwERBwYHFTcVBwYHFSU2PwE2NTE1NxUCpxUGASoVBhsVBujNFQboNiYBXTYmAc8WBer7FQYBByETMAhdey41AkAuNQFaLjUBMV8rLjUCMQFVHy/+5RQBqx4vAf6PLC41ATF3NS81ATgHG0gMDmkUvgAAAAAMAJYAAQAAAAAAAQALABgAAQAAAAAAAgAHADQAAQAAAAAAAwAmAIoAAQAAAAAABAALAMkAAQAAAAAABQALAO0AAQAAAAAABgALAREAAwABBAkAAQAWAAAAAwABBAkAAgAOACQAAwABBAkAAwBMADwAAwABBAkABAAWALEAAwABBAkABQAWANUAAwABBAkABgAWAPkAcwBhAHUAZABpAF8AcgBpAHkAYQBsAABzYXVkaV9yaXlhbAAAUgBlAGcAdQBsAGEAcgAAUmVndWxhcgAARgBvAG4AdABGAG8AcgBnAGUAIAAyAC4AMAAgADoAIABzAGEAdQBkAGkAXwByAGkAeQBhAGwAIAA6ACAAMQAtADMALQAyADAAMgA1AABGb250Rm9yZ2UgMi4wIDogc2F1ZGlfcml5YWwgOiAxLTMtMjAyNQAAcwBhAHUAZABpAF8AcgBpAHkAYQBsAABzYXVkaV9yaXlhbAAAVgBlAHIAcwBpAG8AbgAgADEALgAwAABWZXJzaW9uIDEuMAAAcwBhAHUAZABpAF8AcgBpAHkAYQBsAABzYXVkaV9yaXlhbAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAEAAgADAQIBAwEEC3NhdWRpX3JpeWFsC3NhdWRpX3JpeWFsC3NhdWRpX3JpeWFsAAAAAf//AAIAAQAAAAwAAAAcAAAAAgACAAMABAABAAUABgACAAQAAAACAAAAAAABAAAAANpTmfAAAAAA4+k7wgAAAADj6TvC) format('truetype');
        }

        .riyalsymbol {
            font-family: "saudi_riyal" !important;
        }

    </style>
</head>
<body>
<div id="content" class="w-full" style="display: table; margin: auto;">
    <div style="display: table-cell; vertical-align: middle;  width: 100%;" class="p-2" dir="rtl">
        <p class="riyalsymbol">&#xE900;500</p>
    </div>
</div>
</body>
</html>

```

**Comment by ahmedsayedabdelsalam** [comment]
i also tried to run wkhtmltopdf invoice.html invoice.pdf

the symbol appears on the html but not on the pdf

**Comment by hussain** [comment]
**wkhtmltopdf** will **not load** the font unless there is some content with css `font-family: 'saudi_riyal'`, even if the symbol is there as unicode but there is nothing stating it should use that specific font. This is a known issue in wkhtmltopdf (and might be faced in browsers in some cases).

So either you enforce that using CSS style in HTML or inject dummy content using CSS.

A nice trick is to use CSS to inject some content.

Example:
```scss
// Hidden font injection
// This is a workaround for a known issue with wkhtmltopdf where it doesn't include custom fonts by default
// We must include a dummy content that uses the new font so wkhtmltopdf will include the font
.footer::before {
  content: "\E900"; // Unicode for Saudi Riyal symbol
  font-family: 'saudi_riyal'; // Must be applied here
  position: absolute;
  left: -9999px;
  top: -9999px;
  font-size: 1px;
  width: 1px;
  height: 1px;
  overflow: hidden;
  visibility: hidden;
}
```

**Comment by hussain** [comment]
Can you try using CSS to inject the symbol.

```html
<!doctype html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body {
            margin: 0px;
            width: 100%;
            padding: 0px;
            word-break: break-word;
            -webkit-font-smoothing: antialiased
        }

        .font-sans {
            font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important
        }

        @font-face{
            font-family:'saudi_riyal';
            src: url(data:font/truetype;charset=utf-8;base64,AAEAAAANAIAAAwBQRkZUTaImEXUAAAc0AAAAHEdERUYAOwANAAAHEAAAACRPUy8yVkJa4AAAAVgAAABWY21hcAA179MAAAHIAAABUmdhc3D//wADAAAHCAAAAAhnbHlmXC2lxAAAAywAAAHUaGVhZCt9vCAAAADcAAAANmhoZWEHtwSTAAABFAAAACRobXR4DJ4BeAAAAbAAAAAYbG9jYQCcATgAAAMcAAAAEG1heHAASwA1AAABOAAAACBuYW1l7GTerwAABQAAAAGzcG9zdI0SaQEAAAa0AAAAVAABAAAAAQAAkjtPw18PPPUACwQAAAAAAOPpO8IAAAAA4+k7wgC8ABYD0QOJAAAACAACAAAAAAAAAAEAAAOJAAAAXASNAAAAAAPRAAEAAAAAAAAAAAAAAAAAAAAFAAEAAAAHADIAAgAAAAAAAgAAAAEAAQAAAEAAAAAAAAAAAQOEAZAABQAIApkCzAAAAI8CmQLMAAAB6wAzAQkAAAIABQMAAAAAAAAAAAABEAAAAAAAAAAAAAAAUGZFZABAACDpAAPA/8AAXAOJ/+oAAAABAAAAAAAABAAAAAAAAAABVQAAAgAAAASNALwAvAC8AAAAAwAAAAMAAAAcAAEAAAAAAEwAAwABAAAAHAAEADAAAAAIAAgAAgAAAAAAIOkA//8AAAAAACDpAP//AAD/4xcEAAEAAAAAAAAAAAAAAQYAAAEAAAAAAAAAAQIAAAACAAAAAAAAAAAAAAAAAAAAAQAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATgCcAOoAAgC8ABYD0QOJAAcAMQAAJQYHFSU2NzUnNjc1BzU3Njc1BxEGByMRBxEGDwERBwYHFTcVBwYHFSU2PwE2NTE1NxUCpxUGASoVBhsVBujNFQboNiYBXTYmAc8WBer7FQYBByETMAhdey41AkAuNQFaLjUBMV8rLjUCMQFVHy/+5RQBqx4vAf6PLC41ATF3NS81ATgHG0gMDmkUvgAAAgC8ABYD0QOJAAcAMQAAJQYHFSU2NzUnNjc1BzU3Njc1BxEGByMRBxEGDwERBwYHFTcVBwYHFSU2PwE2NTE1NxUCpxUGASoVBhsVBujNFQboNiYBXTYmAc8WBer7FQYBByETMAhdey41AkAuNQFaLjUBMV8rLjUCMQFVHy/+5RQBqx4vAf6PLC41ATF3NS81ATgHG0gMDmkUvgAAAgC8ABYD0QOJAAcAMQAAJQYHFSU2NzUnNjc1BzU3Njc1BxEGByMRBxEGDwERBwYHFTcVBwYHFSU2PwE2NTE1NxUCpxUGASoVBhsVBujNFQboNiYBXTYmAc8WBer7FQYBByETMAhdey41AkAuNQFaLjUBMV8rLjUCMQFVHy/+5RQBqx4vAf6PLC41ATF3NS81ATgHG0gMDmkUvgAAAAAMAJYAAQAAAAAAAQALABgAAQAAAAAAAgAHADQAAQAAAAAAAwAmAIoAAQAAAAAABAALAMkAAQAAAAAABQALAO0AAQAAAAAABgALAREAAwABBAkAAQAWAAAAAwABBAkAAgAOACQAAwABBAkAAwBMADwAAwABBAkABAAWALEAAwABBAkABQAWANUAAwABBAkABgAWAPkAcwBhAHUAZABpAF8AcgBpAHkAYQBsAABzYXVkaV9yaXlhbAAAUgBlAGcAdQBsAGEAcgAAUmVndWxhcgAARgBvAG4AdABGAG8AcgBnAGUAIAAyAC4AMAAgADoAIABzAGEAdQBkAGkAXwByAGkAeQBhAGwAIAA6ACAAMQAtADMALQAyADAAMgA1AABGb250Rm9yZ2UgMi4wIDogc2F1ZGlfcml5YWwgOiAxLTMtMjAyNQAAcwBhAHUAZABpAF8AcgBpAHkAYQBsAABzYXVkaV9yaXlhbAAAVgBlAHIAcwBpAG8AbgAgADEALgAwAABWZXJzaW9uIDEuMAAAcwBhAHUAZABpAF8AcgBpAHkAYQBsAABzYXVkaV9yaXlhbAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAEAAgADAQIBAwEEC3NhdWRpX3JpeWFsC3NhdWRpX3JpeWFsC3NhdWRpX3JpeWFsAAAAAf//AAIAAQAAAAwAAAAcAAAAAgACAAMABAABAAUABgACAAQAAAACAAAAAAABAAAAANpTmfAAAAAA4+k7wgAAAADj6TvC) format('truetype');
        }

        .riyalsymbol::before {
            font-family: "saudi_riyal" !important;
            content: '\E900';
        }

    </style>
</head>
<body>
<div id="content" class="w-full" style="display: table; margin: auto;">
    <div style="display: table-cell; vertical-align: middle;  width: 100%;" class="p-2" dir="rtl">
        <p class="riyalsymbol">500</p>
    </div>
</div>
</body>
</html>

```

**Comment by hussain** [comment]
> This might not be related to original issue, but it is related to **wkhtmltopdf**

**wkhtmltopdf** will **not load** the font unless there is some content with css `font-family: 'saudi_riyal'`, even if the symbol is there as unicode but there is nothing stating it should use that specific font. This is a known issue in wkhtmltopdf (and might be faced in browsers in some cases).

So either you enforce that using CSS style in HTML or inject dummy content using CSS.

A nice trick is to use CSS to inject some content.

Example:
```scss
// Hidden font injection
// This is a workaround for a known issue with wkhtmltopdf where it doesn't include custom fonts by default
// We must include a dummy content that uses the new font so wkhtmltopdf will include the font
.footer::before {
  content: "\E900"; // Unicode for Saudi Riyal symbol
  font-family: 'saudi_riyal'; // Must be applied here
  position: absolute;
  left: -9999px;
  top: -9999px;
  font-size: 1px;
  width: 1px;
  height: 1px;
  overflow: hidden;
  visibility: hidden;
}
```
