### ISSUE TITLE
Not working for Bold text

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [emran-alhaddad/Saudi-Riyal-Font#13]
![Image](https://github.com/user-attachments/assets/cc393899-e1da-4da2-b3c0-b9bc051bd6b9)

**Comment by emran-alhaddad** [comment]
@ahmedsayedabdelsalam can you share details of the framework and code sample ?

**Comment by ahmedsayedabdelsalam** [comment]
it's working on web but not in react native mobile app
i used the ttf file

**Comment by hussain** [comment]
We are facing same `bold` issue partially but it seems (in our case) it is related to CSS for some HTML tags.

App: Odoo 17.0

`bold` working fine

![Image](https://github.com/user-attachments/assets/3991e98c-4b7f-4c4d-ae69-5ea0302304b2)

`bold` not working fine inside `h2` tag

![Image](https://github.com/user-attachments/assets/42ba4f9f-484d-474c-b838-0d23ea56d345)

**Comment by emran-alhaddad** [comment]
Hello @ahmedsayedabdelsalam @hussain I will check this issue and solve it.

**Comment by emran-alhaddad** [comment]
hello @ahmedsayedabdelsalam @hussain , I just checked this case, it work fine both using direct unicode or css class and bold works fine , can you share full sample of your case so we can fix ?

**Comment by ahmedsayedabdelsalam** [comment]
web will render it because browsers are smart to make font bolder even it's not supported by the font
if you try mobile or pdf it won't work

**Comment by hussain** [comment]
> `bold` not working fine inside `h2` tag
> 
> ![Image](https://github.com/user-attachments/assets/42ba4f9f-484d-474c-b838-0d23ea56d345)
@emran-alhaddad Thanks for checking.

As mentioned before this is related to CSS/SCSS in Odoo itself. We did a fix by explicitly applying the font family to proper tags since all of this is computed in Odoo scss system.

```scss
/**
* Safely inject into body stack without interfering with UI
* This file properly extends Odoo's font stack variables without overriding them.
* Use `body` and `--body-font-family` to override the default font family since using odoo
* theme variables is not working.
* Notes:
* - Odoo 15.0: var(--font-family-sans-serif) is the default font family for the body.
* - Odoo 16.0+: var(--body-font-family) is the default font family for the body.
* - We need to include body, h1-6, .h1-6 to enforce this usage.
* - We might as well need .oe_price and other classes (as we experience).
*/
body,
h1, h2, h3, h4, h5, h6,
.h1, .h2, .h3, .h4, .h5, .h6,
.oe_price
{
    font-family: 'saudi_riyal', var(--body-font-family);
}
```

We will publish a module for Odoo soon, and would share it.
@emran-alhaddad should a page be somewhere or pinned issue to list existing modules/addons/extensions that use this font as a reference?
